services:

  web:
    build:
      context: web
      dockerfile: "../dockerfiles/Dockerfile.frontend"
    ports:
      - "8080:3000"

  backend:
    build:
      context: .
      dockerfile: "dockerfiles/Dockerfile.backend"
    ports:
      - "50051:50051"