apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ include "akasha-chart.name" . }}
    component: web
spec:
  type: {{ .Values.service.web.type }}
  selector:
    app: {{ include "akasha-chart.name" . }}
    component: web
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
      protocol: TCP
      name: http
