apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akasha-chart.name" . }}-web
  labels:
    app: {{ include "akasha-chart.name" . }}
    component: web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "akasha-chart.name" . }}
      component: web
  template:
    metadata:
      labels:
        app: {{ include "akasha-chart.name" . }}
        component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.web.targetPort }}
          env:
            - name: AKASHA_HOST
              value: "{{ .Values.env.web.AKASHA_HOST }}"
