FROM rust:1.79 AS builder
WORKDIR /usr/src/akasha

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y protobuf-compiler

COPY . .
RUN cargo install --path ./backend

RUN ls -la /usr/local/cargo/bin

CMD ["backend"]