[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.3"
serde = { version = "1.0.210", features = ["derive"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
