replicaCount: 1

image:
  web:
    repository: akasha.azurecr.io/akasha-web
    tag: latest
  backend:
    repository: akasha.azurecr.io/akasha-backend
    tag: latest
  pullPolicy: Always

service:
  web:
    type: LoadBalancer
    port: 80
    targetPort: 3000
  backend:
    type: ClusterIP
    port: 50051
    targetPort: 50051

env:
  web:
    AKASHA_HOST: backend  # Hostname of the backend service
  backend:
    AKASHA_STORAGE_TYPE: blob
    AKASHA_STORAGE_BLOB_ACCOUNT: akashadev
    RUST_LOG: info

serviceAccountName: workload-identity-sa
