replicaCount: 1

image:
  web:
    repository: akasha.azurecr.io/akasha-web
    tag: latest
  backend:
    repository: akasha.azurecr.io/akasha-backend
    tag: latest
  pullPolicy: IfNotPresent

service:
  web:
    type: ClusterIP
    port: 8080
    targetPort: 3000
  backend:
    type: ClusterIP
    port: 50051
    targetPort: 50051

env:
  web:
    AKASHA_HOST: backend  # Hostname of the backend service
